workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: StatusKoll

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: se.gotainnovation.statuskoll
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          mkdir -p dist
          npm run build

      - name: Add iOS platform
        script: |
          npx cap add ios || true

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Set up app icons
        script: |
          unzip -o assets/icons.zip -d assets/
          cp -r assets/apple-devices/AppIcon.appiconset/* ios/App/App/Assets.xcassets/AppIcon.appiconset/
          echo "✅ App icons installed"

      - name: Increment build number
        script: |
          cd ios/App
          agvtool new-version -all $(($(date +%s) / 60))

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
