workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: StatusKoll
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: se.gotainnovation.statuskoll
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
      node: v20.14.0
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Add iOS platform if missing
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Install CocoaPods
        script: cd ios/App && pod install
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
