workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: StatusKoll

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: se.gotainnovation.statuskoll
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest

    scripts:
      - name: Install npm dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          mkdir -p dist
          npm run build

      - name: Add iOS platform
        script: |
          npx cap add ios || true

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Set up app icons
        script: |
          unzip -o assets/icons.zip -d assets/
          cp -r assets/apple-devices/AppIcon.appiconset/* ios/App/App/Assets.xcassets/AppIcon.appiconset/
          echo "✅ App icons installed"

      - name: Set version and build number
        script: |
          cd ios/App
          agvtool new-marketing-version 1.2
          agvtool new-version -all $(($(date +%s) / 60))

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Set encryption export compliance
        script: |
          # Declare that app only uses standard Apple/HTTPS encryption (exempt)
          /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" ios/App/App/Info.plist || \
          /usr/libexec/PlistBuddy -c "Set :ITSAppUsesNonExemptEncryption false" ios/App/App/Info.plist
          echo "✅ Export compliance set: No non-exempt encryption"

      - name: Set iPhone only (no iPad)
        script: |
          # Set targeted device family to iPhone only (1 = iPhone, 2 = iPad, 1,2 = both)
          /usr/libexec/PlistBuddy -c "Delete :UIDeviceFamily" ios/App/App/Info.plist 2>/dev/null || true
          /usr/libexec/PlistBuddy -c "Add :UIDeviceFamily array" ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :UIDeviceFamily:0 integer 1" ios/App/App/Info.plist
          echo "✅ Device family set: iPhone only"

      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
